travis:
  secure:
    BINSTAR_TOKEN: qkriSWnqG2cjPxPIhxUuz/sBhSfIq3ddiKOKL3IvPhTCJeIJCVJc257dhZoXvdjVJCylDZcLSuqixcPOC/U6Tl/iLjj3634A/LphaoH2lgzjbRB52o6eTyOEv2azQjmde16+5TAg29OdKqVIbvK4Fb8u77onUe9GhNkHHSqCcj6gsgEcLYtbHHxNz0ll0APlnXyZUCMPcw6yv7BV6LnQFMtAqwauKJ5uf8+vNsfu3RnyIaRobmTbomo2Xqfz7JIyBI28zPt5O1ExkGYXgv5i6v2WMIXHwhs7jCCUKy77qtD188pWb/pB7iFTkrNgvMND/A4mpgNENR15Z7Kb9vFShdvTOZuuU/Es9940lJgsrKmhADzN78DGllJOX2SdtvC9k4sOAF08RVNT0gzZpX0MqK6FBwihf0yVq5eNEHh3yoP2A+Z5X/sOomHNgBbSuOHXGKaIG0m0NfIQjC7VFN/rsI2U019sjuFfkdv/Y8MLENYbyKKmt9Dhv1XYOgOy/RMrT/HYhNhsIeBRngN0sTOx3GKVVDQrsQQt9Z6jC9C3slJbBFkhdj3JUPinPe4x/T4tjQ9KiAmhjMX+2aNYATRJ8qMmx2X+TTGbl+VZxHumYGDKqmCqFdWlimmq4C9FiX2rrf8Tsc9/ec5GyfwV3wfJU76k/y6vuktVkGIO/rwM7Nw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
